config/routes.rb
require "sidekiq/web"
Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"

  namespace :admin, path: "panel-admina" do

    get "/", to: "dashboard#index" 

    resources :pages, path: "strony", except: %i[ show ] do
      collection { get "lista", to: "pages#lista", as: :lista }
    end

    resources :posts, path: "wpisy", except: %i[index show] do
      delete "remove_image/:image_id", to: "posts#remove_image",
                                       as: :remove_image, on: :member
      collection do
        get  "lista", to: "posts#lista",  as: :lista  
      end
    end

    resources :roles, path: "role" do
      collection { get "lista", to: "roles#lista", as: :lista }
    end

    get   "uzytkownicy",        to: "user_panel#index",        as: :users
    patch "uzytkownicy/:id",        to: "user_panel#update_user",  as: :users_save

    post '/upload-image-endpoint', to: 'uploads#image'

  end

  namespace :api do 
    resources :posts, only: %i[ index show ]
    resources :pages, only: %i[ show ]
    resources :contacts, only: %i[ create ]
    resources :current_user, only: [:index]

    namespace :admin do
      resources :posts, only: %i[create update destroy]
      post '/upload-image-endpoint', to: 'uploads#image'
    end
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  resources :posts, path: "wpisy", only: %i[ index show ], as: "wpisy"

  resource :contact, path: "kontakt", only: %i[ show create ]

  root "posts#index"

  get "up" => "rails/health#show", as: :rails_health_check

  get "/*slug", to: "pages#show", as: :site_page, format: false,
    constraints: ->(req) {
      req.path != "/" && !req.path.match?(/\.[a-z0-9]{2,5}$/i)
    }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true, format: { with: /\A[^@\s]+@[^@\s]+\.[^@\s]+\z/ }
  validates :subject, presence: true
  validates :message, presence: true
end

app/models/jwt_denylist.rb
class JwtDenylist < ApplicationRecord
  include Devise::JWT::RevocationStrategies::Denylist

  self.table_name = 'jwt_denylists'
end

app/models/page.rb
class Page < ApplicationRecord
  has_ancestry
  has_rich_text :content
  
  extend FriendlyId
  friendly_id :title, use: :slugged

  validates :title, presence: true, uniqueness: true
  validates :content, presence: true
  validates :slug, presence: true, uniqueness: true

  scope :in_nav, -> { where(in_nav: true) }


  def nav_children
    children.in_nav.order(:title)
  end
  
  def full_slug
    path.map(&:slug).join("/")
  end
end

app/models/pdf.rb
class Pdf < ApplicationRecord
  has_one_attached :file
  validates :url, presence: true, uniqueness: true
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :main_image
  has_many_attached :gallery
  has_rich_text :content
  belongs_to :user

  extend FriendlyId
  friendly_id :title, use: [:slugged, :finders]

  validates :main_image, presence: true
  validates :title, uniqueness: true, presence: true
  validate :custom_date_cannot_be_in_future
  validate :main_image_type
  validate :gallery_image_type

  private

  def main_image_type
    return unless main_image.attached?

    unless main_image.blob&.content_type&.in?(%w[image/jpeg image/png image/webp image/jpg])
      errors.add(:main_image, :invalid_format)
    end
  end

  def gallery_image_type
    return unless gallery.attached?

    gallery.each do |img|
      unless img.blob&.content_type&.in?(%w[image/jpeg image/png image/webp image/jpg])
        errors.add(:gallery, :invalid_format)
      end
    end
  end


  def custom_date_cannot_be_in_future
    if custom_date.present? && custom_date > Date.today
      errors.add(:custom_date, :invalid_date)
    end
  end

end

app/models/role.rb
class Role < ApplicationRecord
  has_many :users
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :jwt_authenticatable, jwt_revocation_strategy: JwtDenylist
      belongs_to :role, optional: true
      before_validation :set_default_role, on: :create
      has_many :posts
      validates :username, presence: true
      validates :email, format: { with: /\A[^@\s]+@[^@\s]+\.[^@\s]+\z/ }

      private

        def set_default_role
          self.role ||= Role.find_by(name: "Użytkownik")
        end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
    @contact = Contact.new
  end
  def create
    @contact = Contact.new(contact_params)

    if @contact.save
      ContactMailer.with(contact: @contact).form_contact.deliver_later
      redirect_to kontakt_path, notice: "Email wysłano poprawnie"
    else
      render :index, status: :unprocessable_entity
    end
  end


  private

  def contact_params
    params.require(:contact).permit(:name, :email, :subject, :message)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def show
    @contact = Contact.new
  end
  
  def create
    @contact = Contact.new(contact_params)

    if @contact.save
      ContactMailer.with(contact: @contact).form_contact.deliver_later
      redirect_to contact_path, notice: "Email wysłano poprawnie"
    else
      render :index, status: :unprocessable_entity
    end
  end


  private

  def contact_params
    params.require(:contact).permit(:name, :email, :subject, :message)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def show
    segments = params[:slug].to_s.split("/")

    @page = segments.reduce(nil) do |parent, slug|
      scope = parent ? parent.children : Page.roots
      scope.friendly.find(slug)
    end

  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show ]
  
  def index
    posts_on_page = 12
    total_posts   = Post.count

    @how_many_page = [(total_posts.to_f / posts_on_page).ceil, 1].max

    page = params[:page].to_i
    page = 1 if page < 1

    if page > @how_many_page
      redirect_to root_path, alert: "Strona niedostępna." and return
    end

    offset  = (page - 1) * posts_on_page
    @posts  = Post.order(Arel.sql("COALESCE(custom_date, updated_at) DESC")).limit(posts_on_page).offset(offset)
  end

  def show
  end

  private
    
    def set_post
      @post = Post.find(params.expect(:id))
    end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/role_helper.rb
module RoleHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/user_panel_helper.rb
module UserPanelHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/admin/lista.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">Tytuł</th>
      <th scope="col">Edytuj</th>
      <th scope="col">Usuń</th>
    </tr>
  </thead>
  <tbody>
  <% if @posts.present? %>
  <% @posts.each do |post| %>
    <tr>
      <td><%= post.title %></td>
      <td><%= link_to "Edytuj", edit_post_path(post.id), class: "btn" %></td>
      <td><%= button_to "Usuń", post, method: :delete, class: "btn" %></td> 
    </tr>
  <% end %>
  <% else %>
  <% @roles.each do |role| %>
    <tr>
      <td><%= role.name %></td>
      <td><%= link_to "Edytuj", edit_role_path(role.id), class: "btn" %></td>
      <td><%= button_to "Usuń", role, method: :delete, class: "btn" %></td> 
    </tr>
  <% end %>
  <% end%>
  </tbody>
</table>
<div>
  <%= link_to "Wróc do panelu admina", panel_admina_path %>
</div>

app/views/admin/pages/_form.html.erb
<% content_for :tiny do %>
  <script src="https://cdn.tiny.cloud/1/omv36n529opjexgf4e04i5dxosf0ldbydjjf8w3td6to1hhc/tinymce/7/tinymce.min.js" referrerpolicy="origin"></script>
  <script>
    tinymce.init({
      selector: '#page_content',
      language: 'pl',
      plugins: 'advlist autolink lists link image charmap preview anchor searchreplace visualblocks code fullscreen insertdatetime media table code help wordcount',
      toolbar: 'undo redo | blocks | bold italic underline forecolor backcolor | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image media | preview code fullscreen',
      images_file_types: 'jpg,svg,webp,png,jpeg',
      file_picker_types: 'file image media',
      automatic_uploads: true,
      images_upload_url: '/panel-admina/upload-image-endpoint',
      media_live_embeds: true,
      relative_urls: false,
      remove_script_host: false,
      convert_urls: true
    });

    </script>
<% end %>

<div class="bd-example m-0">
<%= form_with model: [:admin, @page], local: true do |form| %>
  <% if @page.errors.any? %>
    <div style="color:rgb(226, 19, 54);">
      <h2>Liczba błędów do poprawy przed publikacją wynosi: <%= pluralize(@page.errors.count, "") %></h2>

      <ul>
        <% @page.errors.each do |error| %>
          <li><%= error.message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, "Tytuł strony", class: "form-label d-block" %>
    <%= form.text_field :title, class: "form-control", required: true  %>
  </div>

  <div class="mt-3">
    <%= form.label :content, "Zawartość strony", class: "form-label d-block" %>
    <%= form.textarea :content, class: "form-control"  %>
  </div>

  <div class="mt-3">
    <%= form.label :parent_id, "Wybierz stronę nadrzędną", class: "form-label d-block" %>
    <%= form.collection_select :parent_id, Page.all, :id, :title, {include_blank: "Brak rodzica"}, {class: "form-select"} %>
  </div>

  <div class="form-check mt-3">
    <%= form.label :in_nav, "Strona ma być dodana do nav", class: "form-check-label" %>
    <%= form.checkbox :in_nav, class: "form-check-input" %>
  </div>

  <div>
    <% if action == false || nil %>
      <%= form.submit "Zapisz zmiany", class: "btn mt-3" %>
    <% else %>
      <%= form.submit "Dodaj nową stronę", class: "btn mt-3" %>
    <% end %>
  </div>
<% end %>
</div>

app/views/admin/pages/edit.html.erb
<% content_for :title, "Edytuj stronę" %>

<h1>Edytuj stronę</h1>

<%= render "form", page: @page, action: false %>

<br>

<div>
  <%= link_to "Pokaż tę stronę", site_page_path(@page.path.map(&:slug).join("/")) %> |
  <%= link_to "Wróć", admin_path %>
</div>

app/views/admin/pages/lista.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">Tytuł</th>
      <th scope="col">Edytuj</th>
      <th scope="col">Usuń</th>
    </tr>
  </thead>
  <tbody>
  <% @pages.each do |page| %>
    <tr>
      <td><%= page.title %></td>
      <td><%= link_to "Edytuj", edit_admin_page_path(page.id), class: "btn" %></td>
      <td><%= button_to "Usuń", admin_page_path(page), method: :delete, class: "btn" %></td> 
    </tr>
  <% end %>
  </tbody>
</table>
<div>
  <%= link_to "Wróć", admin_path %>
</div>

app/views/admin/pages/new.html.erb
<% content_for :title, "Nowa strona" %>

<h1>Nowa strona</h1>

<%= render "form", page: @page, action: true %>

<br>

<div>
  <%= link_to "Wróć", admin_path %>
</div>

app/views/admin/users.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">Tytuł</th>
      <th scope="col">Aktualna rola</th>
      <th scope="col">Przydziel inną role</th>
    </tr>
  </thead>
  <tbody>
 <% @users.each do |user| %>
  <tr>
    <td><%= user.email %></td>
    <td><%= user.role.name %></td>
    <td>
        <%= form_with model: user, url: panel_admina_users_save_path(user.id), method: :patch do |form| %>
        <%= form.select :role_name, @roles.map { |role| [role.name, role.name] }, {},class: "form-select" %>
        <%= form.submit "Zapisz rolę", class: "btn mt-2" %>
        <% end %>
    </td>
  </tr>
<% end %>
  </tbody>
</table>
<div>
  <%= link_to "Wróc do panelu admina", panel_admina_path %>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/shared/_notice.html.erb
<aside>
  <div role="alert" id="toast-notice" style="<%= 'display: block; opacity: 1;' if notice.present? %>" aria-live="assertive" aria-atomic="true" class="toast position-fixed" data-bs-autohide="true">
    <div class="toast-header" style="border-color: #88c5c2;">
      <%= image_tag("mainpage/logo.png", class: "rounded me-2", alt: "Logo", style: "width: 30px; height: 30px;") %>
      <strong class="me-auto">Wpisy o życiu</strong>
      <button id="btn-close-toast" type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
    </div>
    <div class="toast-body">
      <%= notice %>
    </div>
  </div>
  <div role="alert" id="toast-alert" style="border-color: #FA003F; <%= 'display: block; opacity: 1;' if alert.present? %>" aria-live="assertive" aria-atomic="true" class="toast position-fixed" data-bs-autohide="true">
    <div class="toast-header" style="border-color: #FA003F;">
      <%= image_tag("mainpage/logo.png", class: "rounded me-2", alt: "Logo", style: "width: 30px; height: 30px;") %>
      <strong class="me-auto">Wpisy o życiu</strong>
      <button id="btn-close-toast-alert" type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
    </div>
    <div class="toast-body">
      <%= alert %>
    </div>
  </div>
  </aside>

app/views/shared/_pdf_icon.html.erb
<% if @pdf.present? %>
  <div class="pdf text-center align-content-center">
    <%= link_to rails_blob_url(@pdf, disposition: "attachment") do %>
    <% image_tag("mainpage/document.png", alt: "Ikonka", class: "pdf-icon") %>
    <% end %>
  </div>
<% end %>