config/routes.rb
require "sidekiq/web"
Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"

  namespace :admin, path: "panel-admina" do

    get "/", to: "dashboard#index" 

    resources :pages, path: "strony", except: %i[ show ] do
      collection { get "lista", to: "pages#lista", as: :lista }
    end

    resources :posts, path: "wpisy", except: %i[index show] do
      delete "remove_image/:image_id", to: "posts#remove_image",
                                       as: :remove_image, on: :member
      collection do
        get  "lista", to: "posts#lista",  as: :lista  
      end
    end

    resources :roles, path: "role" do
      collection { get "lista", to: "roles#lista", as: :lista }
    end

    get   "uzytkownicy",        to: "user_panel#index",        as: :users
    patch "uzytkownicy/:id",        to: "user_panel#update_user",  as: :users_save

    post '/upload-image-endpoint', to: 'uploads#image'

  end

  namespace :api do 
    resources :posts, only: %i[ index show ]
    resources :pages, only: %i[ show ]
    resources :contacts, only: %i[ create ]
    resources :current_user, only: [:index]

    namespace :admin do
      resources :posts, only: %i[create update destroy]
      post '/upload-image-endpoint', to: 'uploads#image'
    end
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  resources :posts, path: "wpisy", only: %i[ index show ], as: "wpisy"

  resource :contact, path: "kontakt", only: %i[ show create ]

  root "posts#index"

  get "up" => "rails/health#show", as: :rails_health_check

  get "/*slug", to: "pages#show", as: :site_page, format: false,
    constraints: ->(req) {
      req.path != "/" && !req.path.match?(/\.[a-z0-9]{2,5}$/i)
    }
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :users
  validates :name, presence: true
end

app/controllers/admin/roles_controller.rb
module Admin
  class RolesController < BaseController
    before_action :authenticate_user!
    before_action :set_role, only: %i[ edit update destroy ]
    before_action :require_roles_permission, only: %i[ new edit lista create update destroy ]
    
    def new
      @role = Role.new
    end

    def edit
    end


    def lista
      @roles = Role.select(:name, :id).order("name ASC")
    end

    def create
      @role = Role.new(role_params)

        if @role.save
          redirect_to admin_path, notice: "Nowa rola utworzona"
        else
          render :new, status: :unprocessable_entity
        end
    end

    def update
        if @role.update(role_params)
          redirect_to admin_path, notice: "Rola zaktualizowana"
        else
          render :edit, status: :unprocessable_entity
        end
    end

    def destroy
      @role.destroy!

      redirect_to lista_admin_roles_path, status: :see_other, notice: "Rola usunięta"
    end

    private
      def set_role
        @role = Role.find(params.expect(:id))
      end

      def role_params
        params.expect(role: [:name,:panelpriv,:postspriv,:rolespriv,:userspriv,:pagespriv])
      end


      def require_roles_permission
        require_permission(:rolespriv)
      end
  end
end

app/helpers/role_helper.rb
module RoleHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/admin/roles/_form.html.erb
<div class="bd-example m-0">
<%= form_with model: [:admin, role], local: true do |form| %>
    <% if role.errors.any? %>
    <div style="color:rgb(226, 19, 54);">
      <h2>Liczba błędów do poprawy wynosi: <%= pluralize(role.errors.count, "") %></h2>
      <ul>
        <% role.errors.each do |error| %>
          <li><%= error.message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, "Nazwa roli", class: "form-label d-block" %>
    <%= form.text_field :name, class: "form-control", required: true %>
  </div>

  <h4 class="mt-2 mb-2">Rola ma mieć uprawienia do:</h4>

  <div class="form-check">
    <%= form.label :panelpriv, "Panel admina", class: "form-check-label" %>
    <%= form.checkbox :panelpriv, class: "form-check-input" %>
  </div>

  <div class="form-check">
    <%= form.label :postspriv, "Zarządzanie wpisami", class: "form-check-label" %>
    <%= form.checkbox :postspriv, class: "form-check-input" %>
  </div>

  <div class="form-check">
    <%= form.label :rolespriv, "Zarządzanie rolami", class: "form-check-label" %>
    <%= form.checkbox :rolespriv, class: "form-check-input" %>
  </div>

  <div class="form-check">
    <%= form.label :userspriv, "Zarządzanie użytkownikami", class: "form-check-label" %>
    <%= form.checkbox :userspriv, class: "form-check-input" %>
  </div>

  <div class="form-check">
    <%= form.label :pagespriv, "Zarządzanie stronami", class: "form-check-label" %>
    <%= form.checkbox :pagespriv, class: "form-check-input" %>
  </div>

  <div>
    <% if action == false or nil %>
      <%= form.submit "Zapisz zmiany", class: "btn mt-2" %>
    <% else %>
      <%= form.submit "Dodaj użytkownika", class: "btn mt-2" %>
    <% end %>
  </div>
<% end %>
</div>

app/views/admin/roles/edit.html.erb
<% content_for :title, "Edycja roli" %>

<h1>Edycja roli</h1>

<%= render "form", role: @role, action: false %>

<br>

<div>
  <%= link_to "Wróć", admin_path %>
</div>

app/views/admin/roles/lista.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">Tytuł</th>
      <th scope="col">Edytuj</th>
      <th scope="col">Usuń</th>
    </tr>
  </thead>
  <tbody>
  <% @roles.each do |role| %>
    <tr>
      <td><%= role.name %></td>
      <td><%= link_to "Edytuj", edit_admin_role_path(role.id), class: "btn" %></td>
      <td><%= button_to "Usuń", admin_role_path(role), method: :delete, class: "btn" %></td> 
    </tr>
  <% end %>
  </tbody>
</table>
<div>
  <%= link_to "Wróć", admin_path %>
</div>

app/views/admin/roles/new.html.erb
<% content_for :title, "Nowa rola" %>

<h1>Nowa rola</h1>

<%= render "form", role: @role, action: true %>

<br>

<div>
  <%= link_to "Wróć", admin_path %>
</div>