config/routes.rb
require "sidekiq/web"
Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"

  namespace :admin, path: "panel-admina" do

    get "/", to: "dashboard#index" 

    resources :pages, path: "strony", except: %i[ show ] do
      collection { get "lista", to: "pages#lista", as: :lista }
    end

    resources :posts, path: "wpisy", except: %i[index show] do
      delete "remove_image/:image_id", to: "posts#remove_image",
                                       as: :remove_image, on: :member
      collection do
        get  "lista", to: "posts#lista",  as: :lista  
      end
    end

    resources :roles, path: "role" do
      collection { get "lista", to: "roles#lista", as: :lista }
    end

    get   "uzytkownicy",        to: "user_panel#index",        as: :users
    patch "uzytkownicy/:id",        to: "user_panel#update_user",  as: :users_save

    post '/upload-image-endpoint', to: 'uploads#image'

  end

  namespace :api do 
    resources :posts, only: %i[ index show ]
    resources :pages, only: %i[ show ]
    resources :contacts, only: %i[ create ]
    resources :current_user, only: [:index]

    namespace :admin do
      resources :posts, only: %i[create update destroy]
      post '/upload-image-endpoint', to: 'uploads#image'
    end
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  resources :posts, path: "wpisy", only: %i[ index show ], as: "wpisy"

  resource :contact, path: "kontakt", only: %i[ show create ]

  root "posts#index"

  get "up" => "rails/health#show", as: :rails_health_check

  get "/*slug", to: "pages#show", as: :site_page, format: false,
    constraints: ->(req) {
      req.path != "/" && !req.path.match?(/\.[a-z0-9]{2,5}$/i)
    }
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :main_image
  has_many_attached :gallery
  has_rich_text :content
  belongs_to :user

  extend FriendlyId
  friendly_id :title, use: [:slugged, :finders]

  validates :main_image, presence: true
  validates :title, uniqueness: true, presence: true
  validate :custom_date_cannot_be_in_future
  validate :main_image_type
  validate :gallery_image_type

  private

  def main_image_type
    return unless main_image.attached?

    unless main_image.blob&.content_type&.in?(%w[image/jpeg image/png image/webp image/jpg])
      errors.add(:main_image, :invalid_format)
    end
  end

  def gallery_image_type
    return unless gallery.attached?

    gallery.each do |img|
      unless img.blob&.content_type&.in?(%w[image/jpeg image/png image/webp image/jpg])
        errors.add(:gallery, :invalid_format)
      end
    end
  end


  def custom_date_cannot_be_in_future
    if custom_date.present? && custom_date > Date.today
      errors.add(:custom_date, :invalid_date)
    end
  end

end

app/controllers/admin/posts_controller.rb
module Admin
  class PostsController < BaseController
    before_action :set_post, only: %i[ edit update destroy ]
    before_action :set_users, only: %i[ edit update ]
    before_action :authenticate_user!, only: %i[ new edit create update destroy lista remove_image ]
    before_action :require_posts_permission, only: %i[ new edit lista create update destroy remove_image ]

    def new
      @post = Post.new
    end

    def edit
      @author_of_post = @post.user.username
    end

    def lista
        @posts = Post.select(:id, :title, :slug).order(Arel.sql("COALESCE(custom_date, updated_at) DESC"))
    end

    def create
      @post = current_user.posts.build(post_params)

      if @post.save
          redirect_to wpisy_path(@post), notice: "Wpis stworzony pomyślnie."
      else
          render :new, status: :unprocessable_entity
      end
    end

    def update
        if @post.update(post_params.except(:gallery))
          if post_params[:gallery]
            post_params[:gallery].each do |new_image|
              @post.gallery.attach(new_image)
            end
          end

          redirect_to wpisy_path(@post), notice: "Wpis zaktualizowany pomyślnie."
        else
          render :edit, status: :unprocessable_entity
        end
    end

    def remove_image
      @post = Post.find(params[:id])
      image = @post.gallery_attachments.find(params[:image_id])

      if image.purge
        redirect_to edit_admin_post_path(@post), notice: "Zdjęcie zostało usunięte."
      else
      render :edit, status: :unprocessable_entity, alert: "Nie znaleziono zdjęcia."
      end
    end


    def destroy
      @post.destroy!

      redirect_to lista_admin_posts_path, status: :see_other, notice: "Wpis usunięty pomyślnie."
    end

    private

      def set_users
        @users = User.select(:id, :username).where("role_id != 7")
      end

      def set_post
        @post = Post.find(params.expect(:id))
      end

      def post_params
        params.expect(post: [:title,:content,:main_image,:custom_date,:user_id,gallery: []])
      end

      def require_posts_permission
        require_permission(:postspriv)
      end
  end
end

app/controllers/api/admin/posts_controller.rb
module Api
  module Admin
    class PostsController < ApplicationController
      before_action :authenticate_user!
      before_action :require_posts_permission
      before_action :set_post, only: %i[update destroy]
      skip_before_action :verify_authenticity_token
      
      def create
        post = current_user.posts.build(post_params.except(:gallery))

        if post.save
          attach_gallery(post)          #  ← dołączamy po zapisie
          render json: { id: post.id, slug: post.slug }, status: :created
        else
          render json: { errors: post.errors.full_messages }, status: :unprocessable_entity
        end
      end

      def update
        if @post.update(post_params.except(:gallery))
          if post_params[:gallery].present?
            post_params[:gallery].each { |img| @post.gallery.attach(img) }
          end
          head :no_content
        else
          render json: { errors: @post.errors.full_messages }, status: :unprocessable_entity
        end
      end

      def destroy
        @post.destroy!
        head :no_content
      end

      private

      def attach_gallery(post)
        return unless post_params[:gallery].present?

        post_params[:gallery].each { |img| post.gallery.attach(img) }
      end

      def set_post
        @post = Post.find(params[:id])
      end

      def post_params
        params.require(:post).permit(
          :title, :content, :main_image, :custom_date, :user_id, gallery: []
        )
      end

      def require_posts_permission
        require_permission(:postspriv)
      end
    end
  end
end

app/controllers/api/posts_controller.rb
module Api
  class PostsController < ApplicationController
    before_action :set_post, only: %i[ show ]
    
    def index
      posts  = Post.with_attached_main_image.includes(:user).order(Arel.sql("COALESCE(custom_date, updated_at) DESC"))

      render json: PostsSerializer.new(posts).serializable_hash
    end

    def show
      render json: PostSerializer.new(@post).serializable_hash
    end

    private
      
      def set_post
        @post = Post.friendly.find(params[:id])
      end

  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show ]
  
  def index
    posts_on_page = 12
    total_posts   = Post.count

    @how_many_page = [(total_posts.to_f / posts_on_page).ceil, 1].max

    page = params[:page].to_i
    page = 1 if page < 1

    if page > @how_many_page
      redirect_to root_path, alert: "Strona niedostępna." and return
    end

    offset  = (page - 1) * posts_on_page
    @posts  = Post.order(Arel.sql("COALESCE(custom_date, updated_at) DESC")).limit(posts_on_page).offset(offset)
  end

  def show
  end

  private
    
    def set_post
      @post = Post.find(params.expect(:id))
    end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<% content_for :tiny do %>
  <script src="https://cdn.tiny.cloud/1/omv36n529opjexgf4e04i5dxosf0ldbydjjf8w3td6to1hhc/tinymce/7/tinymce.min.js" referrerpolicy="origin"></script>
  <script>
    tinymce.init({
      selector: '#post_content',
      language: 'pl',
      plugins: 'advlist autolink lists link image charmap preview anchor searchreplace visualblocks code fullscreen insertdatetime media table code help wordcount',
      toolbar: 'undo redo | blocks | bold italic underline forecolor backcolor | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image media | preview code fullscreen',
      images_file_types: 'jpg,svg,webp,png,jpeg',
      file_picker_types: 'file image media',
      automatic_uploads: true,
      images_upload_url: '/upload-image-endpoint',
      media_live_embeds: true,
      relative_urls: false,
      remove_script_host: false,
      convert_urls: true
    });

    </script>
<% end %>

<div class="bd-example m-0">
<%= form_with model: [:admin, @post], local: true do |form| %>
  <% if post.errors.any? %>
    <div style="color:rgb(226, 19, 54);">
      <h2>Liczba błędów do poprawy przed publikacją wynosi: <%= pluralize(post.errors.count, "") %></h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mt-3">
    <%= form.label :title, "Tytuł", class: "form-label d-block" %>
    <%= form.text_field :title, class: "form-control", required: true %>
  </div>

  <div class="mt-3">
    <%= form.label :content, "Treść", class: "form-label d-block mt-2" %>
    <%= form.textarea :content, class: "form-control" %>
  </div>

  <% if action == false or nil %>
    <div class="mt-3">
      <p>Aktualna data wpisu to: <%= post.custom_date&.strftime("%d.%m.%Y") || post.updated_at.strftime("%d.%m.%Y") %></p>
      <%= form.label :custom_date, "Zmień date wpisu na:", class: "form-label d-block" %>
      <%= form.date_field :custom_date, class: "form-control" %>
    </div>


    <div class="mt-3">
      <p>Aktualny autor wpisu to: <%= @author_of_post %></p>
      <%= form.label :user_id, "Zmień autora wpisu na:", class: "form-label d-block" %>
      <%= form.select :user_id, @users.map { |user| [user.username, user.id] }, {}, class: "form-select" %>
    </div>

  <% end %>

  <div class="mt-3">
      <%= form.label :main_image, "Główne zdjęcie", class: "form-label d-block mt-2" %>
      <% if post.main_image.attached? %>
        <%= form.file_field :main_image, direct_upload: true, data: { previews_target: "input", action: "change->previews#preview"}, accept: "image/*", class: "form-control" %>
      <% else %>
        <%= form.file_field :main_image, direct_upload: true, data: { previews_target: "input", action: "change->previews#preview"}, required: true, accept: "image/*", class: "form-control" %>
      <% end %>
  </div>

  <%# <div class="mt-3"> %>
      <%# <%= render "image_preview", form: form, post: post, class: "image" %> 
  <%# </div> %>

  <div class="mt-3">
      <% if post.gallery.attached? %>
        <%= form.label :gallery, "Dodaj zdjęcie do galerii zdjęć", class: "form-label d-block mt-2" %>
        <%= form.file_field :gallery, direct_upload: true, accept: "image/*", multiple: true, class: "form-control" %>
      <% else %>
        <%= form.label :gallery, "Galeria zdjęć", class: "form-label d-block mt-2" %>
        <%= form.file_field :gallery, direct_upload: true, accept: "image/*", multiple: true, class: "form-control" %>
      <% end %>
  </div>

  <div class="mt-3">
    <% if action == false or nil %>
      <%= form.submit "Zapisz zmiany", class: "btn mt-2" %>
    <% else %>
      <%= form.submit "Dodaj nowy wpis", class: "btn mt-2" %>
    <% end %>
  </div>
<% end %>

<div class="mt-3">
      <% if post.gallery.attached? %>
        <div class="mb-3">
          <h2>Aktualna galeria zdjęć</h2>
            <div class="d-flex gap-2 flex-wrap">
              <% post.gallery.each do |img| %>
                <div class="d-flex flex-column">
                  <div class="gallery-img" style="background-image: url('<%= url_for(img) %>');"></div>
                  <%= button_to "Usuń to zdjęcie", remove_image_admin_post_path(post, img.id), method: :delete, class: "btn mt-2" %>
                </div>
              <% end %>
            </div>
        </div>
      <% end %>
  </div>
</div>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <div class="card" style="width: 18rem;">
    <%= image_tag(post.main_image, class: "card-img-top", alt: post.title, loading: "lazy") if post.main_image.attached? %>
    <div class="card-body">
      <h2 class="card-title m-0"><%= post.title %></h2>
      <div style="font-size: 16px; color: grey; font-style: italic;"><p class="m-0 p-0">Autor: <%= post.user.username %></p></div>
      <div class="mb-2" style="font-size: 16px; color: grey; font-style: italic;"><p>Data: <%= post.custom_date&.strftime("%d.%m.%Y") || post.updated_at.strftime("%d.%m.%Y") %></p></div>
      <p class="card-text" style="font-size: 18px;"><%= post.content.to_plain_text.truncate(100, separator: '.') %></p>
      <%= link_to "Czytaj więcej ->", wpisy_path(post), class: "btn" %>
    </div>
  </div>
</div>

app/views/posts/_single_post.html.erb
<div id="<%= dom_id post %>">
  <% content_for :title, post.title %>
  <% content_for :desc, post.content.to_plain_text.truncate(100, separator: '.') %>
  <h1 class="text-center"><%= post.title %></h1>

  <div>
    <%= post.content %>
  </div>
  <% if post.gallery.attached? %>
    <div>
      <h2>Galeria zdjęć</h2>
        <div class="d-flex gap-2 flex-wrap">
          <% post.gallery.each do |img| %>
            <div class="gallery-img" style="background-image: url('<%= url_for(img) %>');"></div>
          <% end %>
        </div>
    </div>
  <% end %>
</div>

app/views/posts/index.html.erb
<% content_for :title, "Wpisy" %>

<h1>Wpisy o życiu</h1>
<p>Sint in ea eiusmod qui cupidatat sunt voluptate id nostrud pariatur Lorem enim. SIpsum Lorem adipisicing Lorem cillum ex aliqua elit tempor. In ea consequat exercitation cillum id. Duis do id officia dolore ipsum proident anim consectetur exercitation aliquip do ullamco. Mollit dolor officia incididunt dolore.</p>

<div class="d-flex flex-wrap gap-5" id="posts">
  <% @posts&.each do |post| %>
    <%= render post %>
  <% end %>
</div>

<% if @how_many_page > 1 %>
<% current_page = params[:page].present? ? params[:page].to_i : 1 %>
  <div class="d-flex justify-content-center mt-4 gap-2">
  <% @how_many_page.times do |i| %>
      <% page_number = i + 1 %>
      <% active_class = (current_page == page_number) ? "active-pagination" : "" %>
      <%= link_to page_number, root_path(page: page_number), class: "pagination-links text-center align-content-center #{active_class}" %>
  <% end %>
  </div>
<% end %>

app/views/posts/lista.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">Tytuł</th>
      <th scope="col">Edytuj</th>
      <th scope="col">Usuń</th>
    </tr>
  </thead>
  <tbody>
  <% @posts.each do |post| %>
    <tr>
      <td><%= post.title %></td>
      <td><%= link_to "Edytuj", edit_admin_post_path(post.id), class: "btn" %></td>
      <td><%= button_to "Usuń", admin_post_path(post), method: :delete, class: "btn" %></td> 
    </tr>
  <% end %>
  </tbody>
</table>
<div>
  <%= link_to "Wróc do panelu admina", admin_path %>
</div>

app/views/posts/new.html.erb
<% content_for :title, "Nowy wpis" %>

<h1>Nowy wpis</h1>

<%= render "form", post: @post, action: true %>


<div>
  <%= link_to "Wróc do panelu admina", admin_path %>
</div>

app/views/posts/show.html.erb
<%= render "single_post", post: @post %>